version: "3"
services:
  auth:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - PORT=6969
    volumes:
      - ./:/home/node/app
    ports:
      - "6969:6969"
    links:
      - "db:mongo"
    command: "yarn test"

  db:
    image: mongo
    ports:
      - "27017:27017"